/* GENERATED by deck-build/build-sites.js, do not edit by hand. */
window.LK = {
 "generated": "2026-08-17",
 "scenario": "ampleEquity",
 "selectable": [
  "ampleEquity"
 ],
 "assumptions": {
  "redeemsPerMonth": {
   "resident": 270,
   "longevity": 875
  },
  "blendedMemberDiscount": 0.08,
  "circuitVisitsPerMonth": {
   "resident": 5,
   "longevity": 8,
   "dayPass": 1
  },
  "circuitCostPerVisit": 8,
  "clubHoursPerDay": 14,
  "daysPerMonth": 30.4,
  "clinicalHoursPerDay": 10,
  "clinicalDaysPerMonth": 26,
  "circuitPracticalUtilization": 0.5,
  "treatmentRoomUtilization": 0.65,
  "plungeThroughputPerHour": 7.5,
  "procedureHoursEach": 1,
  "redLightSessionHours": 0.5,
  "orBlockDaysPerMonth": 9,
  "orHoursPerDay": 10,
  "orUtilization": 0.7,
  "orHoursPerCase": 1.75,
  "primeRate": 0.0675,
  "sbaMaxSpread": 0.0275,
  "loanTermMonths": 120,
  "interestOnlyMonths": 18,
  "constructionMonths": 6,
  "avgConstructionDraw": 0.5,
  "equityInjectionFloor": 0.1,
  "equityInjectionPlanning": 0.2,
  "dscrThreshold": 1.25,
  "foundingPrepay": 3600,
  "foundingListPrice": 5400,
  "sbaRate": 0.095
 },
 "tiers": [
  {
   "id": "daypass",
   "name": "Day Pass",
   "cadence": "per visit",
   "price": 75,
   "blurb": "One visit to the recovery circuit. Book any procedure at list price.",
   "includes": [
    "Single circuit visit",
    "Procedures at list price",
    "No events or lounge privileges"
   ],
   "counts": {
    "lean": 190,
    "ample": 275,
    "surgical": 275
   },
   "isMembership": false
  },
  {
   "id": "friends",
   "name": "Friends of L&K",
   "cadence": "per year",
   "price": 300,
   "blurb": "The on-ramp. Member pricing without club access.",
   "includes": [
    "Member pricing on all procedures",
    "Priority booking window",
    "Invitations to open events",
    "No club or circuit access"
   ],
   "counts": {
    "lean": 750,
    "ample": 900,
    "surgical": 900
   },
   "isMembership": true,
   "monthly": 25,
   "usesCircuit": false
  },
  {
   "id": "resident",
   "name": "Resident",
   "cadence": "per month",
   "price": 450,
   "blurb": "The core membership. Where the club actually lives.",
   "includes": [
    "Rolling monthly credit bank",
    "Unlimited recovery circuit",
    "Member pricing on all procedures",
    "1 guest pass per month",
    "Member events"
   ],
   "counts": {
    "lean": 300,
    "ample": 350,
    "surgical": 350
   },
   "isMembership": true,
   "monthly": 450,
   "usesCircuit": true,
   "capped": true
  },
  {
   "id": "longevity",
   "name": "Longevity",
   "cadence": "per month",
   "price": 1250,
   "blurb": "Physician-delivered. Hard capped.",
   "includes": [
    "Everything in Resident",
    "Quarterly physician consult",
    "Annual biomarker panel, DEXA and DUTCH",
    "Therapeutic medications included",
    "4 guest passes per month",
    "Private buyout privileges"
   ],
   "counts": {
    "lean": 32,
    "ample": 40,
    "surgical": 40
   },
   "isMembership": true,
   "monthly": 1250,
   "usesCircuit": true,
   "capped": true
  }
 ],
 "surgicalMenu": {
  "or": [
   "Blepharoplasty, upper, lower and combined",
   "Brow lift",
   "Otoplasty",
   "Chin augmentation and implant",
   "Buccal fat removal",
   "Facial fat grafting and transfer",
   "Liposuction, single or limited area, awake tumescent",
   "Submental neck contouring",
   "Limited body-contouring revision",
   "Scar revision, facial and body",
   "Nasal valve procedures sold as elective self-pay"
  ],
  "treatment": [
   "Lipoma removal",
   "Cyst removal",
   "Benign lesion removal",
   "Ablative laser resurfacing",
   "Skin tightening",
   "Hair restoration surgery and transplant"
  ],
  "excluded": [
   [
    "Breast augmentation, lift, implant exchange or removal",
    "General anesthesia in standard practice"
   ],
   [
    "Facelift and neck lift",
    "General anesthesia; recovery well beyond two hours"
   ],
   [
    "Cosmetic and revision rhinoplasty",
    "Airway risk from pharyngeal blood; general anesthesia standard"
   ],
   [
    "Mini and full abdominoplasty",
    "General anesthesia; extended recovery and caregiver discharge"
   ]
  ]
 },
 "market": [
  {
   "id": "wellness-economy",
   "value": "$6.8T",
   "label": "Global wellness economy, 2024",
   "note": "Grew 7.9% from 2023 to 2024 and has doubled in size since 2013.",
   "source": "Global Wellness Institute",
   "url": "https://globalwellnessinstitute.org/press-room/statistics-and-facts/"
  },
  {
   "id": "medspa-global",
   "value": "$27.8B",
   "label": "Global medical spa market, 2026",
   "note": "Up from $24.2B in 2025, projected to $78.2B by 2033 at a 15.9% CAGR. North America holds 41.2% of it, roughly $10B.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "medspa-count",
   "value": "10,488",
   "label": "US medical spas, 2023",
   "note": "Up from 8,899 in 2022. The category is being built out right now, which is both the opportunity and the reason to differentiate.",
   "source": "Grand View Research",
   "url": "https://www.grandviewresearch.com/industry-analysis/medical-spa-market"
  },
  {
   "id": "consumer-priority",
   "value": "82%",
   "label": "US consumers calling wellness a top or important priority",
   "note": "The US consumer wellness market runs near $480B and is growing up to 10% a year.",
   "source": "McKinsey",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "concierge",
   "value": "$19.4B",
   "label": "US concierge medicine market by 2034",
   "note": "From about $8B in 2025. Longevity services are overwhelmingly elective, cash-pay, and increasingly sold through membership and concierge structures.",
   "source": "Cited in Patientfy longevity market map",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "glp1",
   "value": "1 in 8",
   "label": "US adults currently taking a GLP-1",
   "note": "For a hormone and longevity practice this is a front door, not a fad line item.",
   "source": "KFF",
   "url": "https://patientfy.ai/blog/longevity-medicine-market-2026"
  },
  {
   "id": "longevity-retreats",
   "value": "$11.1B",
   "label": "Longevity retreats market, 2026",
   "note": "From $9.82B in 2025, projected to $17.8B at a 12.6% CAGR.",
   "source": "Research and Markets",
   "url": "https://www.researchandmarkets.com/reports/6226679/longevity-retreats-market-report"
  }
 ],
 "catchment": [
  {
   "id": "income",
   "value": "$129,942",
   "label": "Playa Vista median household income",
   "note": "Against a Los Angeles County median well below it. This is a cash-pay market.",
   "source": "US Census Bureau, via Point2Homes",
   "url": "https://www.point2homes.com/US/Neighborhood/CA/Los-Angeles/Playa-Vista-Demographics.html"
  },
  {
   "id": "tech-companies",
   "value": "500+",
   "label": "Technology companies in Silicon Beach",
   "note": "The Westside tech corridor that Playa Vista sits at the center of.",
   "source": "Wikipedia, Silicon Beach",
   "url": "https://en.wikipedia.org/wiki/Silicon_Beach"
  },
  {
   "id": "campus-jobs",
   "value": "~5,100",
   "label": "Employed at The Campus at Playa Vista",
   "note": "Up from roughly 2,000 in 2015, a 150% increase. A dense, high-income daytime population inside walking distance.",
   "source": "Los Angeles Business Journal",
   "url": "https://labusinessjournal.com/real-estate/workers-silicon-beach-find-coast-costly/"
  }
 ],
 "geography": [
  "Playa Vista",
  "Marina del Rey",
  "Culver City",
  "Venice",
  "Santa Monica",
  "Playa del Rey",
  "El Segundo",
  "Westchester",
  "Mar Vista",
  "Manhattan Beach"
 ],
 "location": {
  "heading": "Silicon Beach, at its densest.",
  "lead": [
   {
    "t": "Playa Vista is a master-planned innovation district on the old Hughes Aircraft site, and it has become the centre of gravity for the Westside’s technology, media, advertising and creator economy. "
   },
   {
    "t": "Google, YouTube and Meta campuses sit within a walk of one another.",
    "em": true
   },
   {
    "t": " LAX is four miles south, the studios fifteen minutes north, and the district was designed to be walked rather than driven."
   }
  ],
  "intro": "The result is a patient market most operators can only describe aspirationally: high-earning, health-literate, time-poor, and already paying cash for injectables, recovery and labs.",
  "close": [
   {
    "t": "Just not in one building.",
    "rose": true
   },
   {
    "t": " Today that is four addresses, four intakes and four bills. The facility that collapses them into one is what this capital builds, and it is being built where those people already are."
   }
  ],
  "source": "Playa Vista district detail verified by the operator, August 2026. The three figures above carry their own sources."
 },
 "scenarios": {
  "ampleEquity": {
   "key": "ampleEquity",
   "label": "Ample · private",
   "menu": "current",
   "projectCost": 4750000,
   "sqft": 4925,
   "tagline": "Full contrast suite, owned equipment, the facility the brand deserves.",
   "equipmentStrategy": "Purchased where payback justifies it",
   "stations": {
    "treatment": 3,
    "ivchair": 8,
    "sauna": 2,
    "plunge": 2,
    "aescape": 1,
    "ammortal": 1,
    "hbot": 1,
    "redlight": 2,
    "diagnostic": 2,
    "dexa": 1,
    "recovery": 4
   },
   "foundingMembers": 150,
   "space": [
    [
     "Arrival, concierge, retail",
     350
    ],
    [
     "The Lounge",
     700
    ],
    [
     "Contrast suite (2 saunas, 2 plunges)",
     250
    ],
    [
     "Aescape",
     120
    ],
    [
     "Ammortal chamber",
     90
    ],
    [
     "Hyperbaric room (seated)",
     120
    ],
    [
     "Red light beds (2)",
     150
    ],
    [
     "IV and regenerative lounge (8 chairs)",
     375
    ],
    [
     "Treatment rooms (3)",
     300
    ],
    [
     "Diagnostics and consult (2)",
     250
    ],
    [
     "Diagnostic imaging (GE iDXA densitometer)",
     125
    ],
    [
     "Locker, shower, changing, bathrooms",
     550
    ],
    [
     "Admin offices (2)",
     200
    ],
    [
     "Kitchen and breakroom",
     200
    ],
    [
     "Storage",
     150
    ],
    [
     "MEP",
     75
    ],
    [
     "Biohazard and linen closets",
     30
    ],
    [
     "Circulation and grossing factor",
     890
    ]
   ],
   "opex": {
    "Rent (4,925 SF NNN)": 27087.5,
    "Clinical and club staff": 85920,
    "Admin and management": 18500,
    "Marketing and member acquisition": 30000,
    "Malpractice and liability": 12000,
    "Equipment leases": 16555,
    "Utilities, software, member platform": 16000,
    "Licensing and compliance": 1610
   },
   "useOfFunds": [
    [
     "Buildout and tenant improvements (4,925 SF @ $250/SF)",
     1231250
    ],
    [
     "Wet areas: 2 saunas, 2 plunges, steam, drainage, ventilation",
     465000
    ],
    [
     "Medical and aesthetic equipment (purchased)",
     780000
    ],
    [
     "Recovery technology: HBOT purchased, Ammortal deposit",
     165950
    ],
    [
     "GE iDXA bone densitometer, purchased",
     25000
    ],
    [
     "FF&E, lounge, millwork, retail",
     430000
    ],
    [
     "Pre-opening: licensing, legal, insurance, hiring",
     310000
    ],
    [
     "Brand, launch, founding member campaign",
     237000
    ],
    [
     "Working capital reserve",
     1105800
    ]
   ],
   "dataKey": "ample",
   "allEquity": true,
   "shortLabel": "Private",
   "lines": [
    {
     "id": "aescape",
     "name": "Aescape Robotic Massage",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 70,
     "room": "aescape",
     "sessions": 200,
     "gross": 14000,
     "cogs": 2520.000000000001,
     "net": 11480
    },
    {
     "id": "ammortal",
     "name": "Ammortal Chamber",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 140,
     "room": "ammortal",
     "sessions": 120,
     "gross": 16800,
     "cogs": 3024.000000000001,
     "net": 13776
    },
    {
     "id": "redlight",
     "name": "Red Light Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 60,
     "room": "redlight",
     "sessions": 650,
     "gross": 39000,
     "cogs": 7020.000000000002,
     "net": 31979.999999999996
    },
    {
     "id": "hbot",
     "name": "Hyperbaric Oxygen",
     "cat": "Recovery",
     "margin": 0.8,
     "price": 200,
     "room": "hbot",
     "sessions": 50,
     "gross": 10000,
     "cogs": 1999.9999999999995,
     "net": 8000
    },
    {
     "id": "compress",
     "name": "Compression Therapy",
     "cat": "Recovery",
     "margin": 0.82,
     "price": 45,
     "room": "recovery",
     "sessions": 225,
     "gross": 10125,
     "cogs": 1822.5000000000005,
     "net": 8302.5
    },
    {
     "id": "prpHair",
     "name": "PRP: Hair & Scalp",
     "cat": "PRP",
     "margin": 0.72,
     "price": 995,
     "room": "treatment",
     "sessions": 33,
     "gross": 32835,
     "cogs": 9193.800000000001,
     "net": 23641.2
    },
    {
     "id": "prpFace",
     "name": "PRP: Face & Aesthetic",
     "cat": "PRP",
     "margin": 0.68,
     "price": 700,
     "room": "treatment",
     "sessions": 35,
     "gross": 24500,
     "cogs": 7839.999999999999,
     "net": 16660
    },
    {
     "id": "prpScar",
     "name": "PRP: Scar & Skin Repair",
     "cat": "PRP",
     "margin": 0.65,
     "price": 600,
     "room": "treatment",
     "sessions": 10,
     "gross": 6000,
     "cogs": 2100,
     "net": 3900
    },
    {
     "id": "prpSoft",
     "name": "PRP: Soft Tissue",
     "cat": "PRP",
     "margin": 0.65,
     "price": 1000,
     "room": "treatment",
     "sessions": 25,
     "gross": 25000,
     "cogs": 8750,
     "net": 16250
    },
    {
     "id": "prpJoint",
     "name": "PRP: Joint & Cartilage",
     "cat": "PRP",
     "margin": 0.62,
     "price": 1200,
     "room": "treatment",
     "sessions": 25,
     "gross": 30000,
     "cogs": 11400,
     "net": 18600
    },
    {
     "id": "prpPost",
     "name": "PRP: Post-procedure",
     "cat": "PRP",
     "margin": 0.6,
     "price": 650,
     "room": "treatment",
     "sessions": 15,
     "gross": 9750,
     "cogs": 3900,
     "net": 5850
    },
    {
     "id": "ivBasic",
     "name": "Basic Hydration",
     "cat": "Regenerative",
     "margin": 0.68,
     "price": 99,
     "room": "ivchair",
     "sessions": 71,
     "gross": 7029,
     "cogs": 2249.2799999999997,
     "net": 4779.72
    },
    {
     "id": "ivMyers",
     "name": "Myers Cocktail",
     "cat": "Regenerative",
     "margin": 0.56,
     "price": 199,
     "room": "ivchair",
     "sessions": 34,
     "gross": 6766,
     "cogs": 2977.0399999999995,
     "net": 3788.9600000000005
    },
    {
     "id": "ivRecovery",
     "name": "Recovery / Hangover",
     "cat": "Regenerative",
     "margin": 0.62,
     "price": 249,
     "room": "ivchair",
     "sessions": 34,
     "gross": 8466,
     "cogs": 3217.08,
     "net": 5248.92
    },
    {
     "id": "ivImmunity",
     "name": "Immunity / High-Dose C",
     "cat": "Regenerative",
     "margin": 0.61,
     "price": 289,
     "room": "ivchair",
     "sessions": 25,
     "gross": 7225,
     "cogs": 2817.75,
     "net": 4407.25
    },
    {
     "id": "ivBeauty",
     "name": "Beauty / Glutathione",
     "cat": "Regenerative",
     "margin": 0.66,
     "price": 165,
     "room": "ivchair",
     "sessions": 57,
     "gross": 9405,
     "cogs": 3197.7,
     "net": 6207.3
    },
    {
     "id": "ivAthletic",
     "name": "Athletic Performance",
     "cat": "Regenerative",
     "margin": 0.65,
     "price": 249,
     "room": "ivchair",
     "sessions": 40,
     "gross": 9960,
     "cogs": 3486,
     "net": 6474
    },
    {
     "id": "nad100",
     "name": "NAD+ 100mg",
     "cat": "Regenerative",
     "margin": 0.74,
     "price": 289,
     "room": "ivchair",
     "sessions": 25,
     "gross": 7225,
     "cogs": 1878.5,
     "net": 5346.5
    },
    {
     "id": "nad250",
     "name": "NAD+ 250mg",
     "cat": "Regenerative",
     "margin": 0.76,
     "price": 350,
     "room": "ivchair",
     "sessions": 33,
     "gross": 11550,
     "cogs": 2772,
     "net": 8778
    },
    {
     "id": "nad500",
     "name": "NAD+ 500mg",
     "cat": "Regenerative",
     "margin": 0.78,
     "price": 550,
     "room": "ivchair",
     "sessions": 33,
     "gross": 18150,
     "cogs": 3992.9999999999995,
     "net": 14157
    },
    {
     "id": "imShot",
     "name": "IM Shot: B12 / Lipo",
     "cat": "Regenerative",
     "margin": 0.65,
     "price": 95,
     "room": "ivchair",
     "sessions": 58,
     "gross": 5510,
     "cogs": 1928.4999999999998,
     "net": 3581.5
    },
    {
     "id": "thermeds",
     "name": "Therapeutic medications",
     "cat": "Regenerative",
     "margin": 0.75,
     "price": 300,
     "room": "treatment",
     "sessions": 60,
     "gross": 18000,
     "cogs": 4500,
     "net": 13500
    },
    {
     "id": "botox",
     "name": "Botox (15-unit minimum)",
     "cat": "Aesthetics",
     "margin": 0.7,
     "price": 240,
     "room": "treatment",
     "sessions": 80,
     "gross": 19200,
     "cogs": 5760.000000000001,
     "net": 13440
    },
    {
     "id": "filler",
     "name": "Filler (0.5 ml)",
     "cat": "Aesthetics",
     "margin": 0.65,
     "price": 850,
     "room": "treatment",
     "sessions": 56,
     "gross": 47600,
     "cogs": 16660,
     "net": 30940
    },
    {
     "id": "rfmicro",
     "name": "RF Microneedling",
     "cat": "Aesthetics",
     "margin": 0.75,
     "price": 1000,
     "room": "treatment",
     "sessions": 50,
     "gross": 50000,
     "cogs": 12500,
     "net": 37500
    },
    {
     "id": "laser",
     "name": "Laser Platform",
     "cat": "Aesthetics",
     "margin": 0.7,
     "price": 850,
     "room": "treatment",
     "sessions": 30,
     "gross": 25500,
     "cogs": 7650.000000000001,
     "net": 17850
    },
    {
     "id": "biometric",
     "name": "Advanced Biometrics",
     "cat": "Diagnostics",
     "margin": 0.7,
     "price": 225,
     "room": "diagnostic",
     "sessions": 20,
     "gross": 4500,
     "cogs": 1350.0000000000002,
     "net": 3150
    },
    {
     "id": "dna",
     "name": "DNA Analysis",
     "cat": "Diagnostics",
     "margin": 0.67,
     "price": 600,
     "room": "diagnostic",
     "sessions": 15,
     "gross": 9000,
     "cogs": 2969.9999999999995,
     "net": 6030
    },
    {
     "id": "dutch",
     "name": "DUTCH Plus Test",
     "cat": "Diagnostics",
     "margin": 0.65,
     "price": 750,
     "room": "diagnostic",
     "sessions": 20,
     "gross": 15000,
     "cogs": 5250,
     "net": 9750
    },
    {
     "id": "dexa",
     "name": "DEXA Scan",
     "cat": "Diagnostics",
     "margin": 0.77,
     "price": 95,
     "room": "diagnostic",
     "sessions": 95,
     "gross": 9025,
     "cogs": 2075.75,
     "net": 6949.25
    }
   ],
   "rackValue": 507121,
   "serviceCogs": 146802.9,
   "redeemed": 129500,
   "alaCarteGross": 377621,
   "memberDiscount": 30209.68,
   "alaCarteNet": 347411.32,
   "membershipLines": [
    {
     "id": "friends",
     "name": "Friends of L&K",
     "count": 900,
     "monthly": 22500
    },
    {
     "id": "resident",
     "name": "Resident",
     "count": 350,
     "monthly": 157500
    },
    {
     "id": "longevity",
     "name": "Longevity",
     "count": 40,
     "monthly": 50000
    }
   ],
   "membershipRevenue": 230000,
   "accessRevenue": 20625,
   "totalRevenue": 598036.3200000001,
   "circuitCogs": 18760,
   "totalCogs": 165562.9,
   "netAfterCogs": 432473.42000000004,
   "blendedMargin": 0.7231557775621387,
   "serviceMargin": 0.7105170166488866,
   "redemptionRatio": 0.6240963855421687,
   "opexTotal": 207672.5,
   "operatingIncome": 224800.92000000004,
   "operatingIncomeAnnual": 2697611.0400000005,
   "operatingMargin": 0.37589844041579284,
   "revenueAnnual": 7176435.840000001,
   "injectionFloor": 4750000,
   "injectionPlanning": 4750000,
   "loanFloor": 0,
   "loanPlanning": 0,
   "isPrivate": false,
   "injectionPct": 1,
   "monthlyDebt": 0,
   "annualDebt": 0,
   "interestOnlyPayment": 0,
   "dscr": null,
   "unleveredYield": 0.5679181136842106,
   "rateBand": [],
   "founding": {
    "count": 150,
    "prepay": 3600,
    "discount": 0.33333333333333337,
    "proceeds": 540000
   },
   "capacity": {
    "operatingRoom": null,
    "circuit": {
     "theoretical": 6384,
     "practical": 3192,
     "demand": 2345,
     "utilization": 0.7346491228070177,
     "headroom": 847
    },
    "treatmentRooms": {
     "theoretical": 780,
     "practical": 507,
     "demand": 419,
     "utilization": 0.8264299802761341,
     "headroom": 88
    },
    "redLight": {
     "beds": 2,
     "theoretical": 1702,
     "practical": 851,
     "demand": 650,
     "utilization": 0.7636278195488723,
     "headroom": 201
    }
   },
   "ramp": [
    {
     "month": 1,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 0,
     "foundingProceeds": 90000,
     "netCash": 17315,
     "cumulativeCash": 17315
    },
    {
     "month": 2,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 0,
     "foundingProceeds": 90000,
     "netCash": 17315,
     "cumulativeCash": 34629
    },
    {
     "month": 3,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 0,
     "foundingProceeds": 90000,
     "netCash": 17315,
     "cumulativeCash": 51944
    },
    {
     "month": 4,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 0,
     "foundingProceeds": 90000,
     "netCash": 17315,
     "cumulativeCash": 69259
    },
    {
     "month": 5,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 0,
     "foundingProceeds": 90000,
     "netCash": 17315,
     "cumulativeCash": 86573
    },
    {
     "month": 6,
     "maturity": 0,
     "open": false,
     "revenue": 0,
     "cogs": 0,
     "opex": 72685,
     "operating": -72685,
     "debtService": 0,
     "foundingProceeds": 90000,
     "netCash": 17315,
     "cumulativeCash": 103888
    },
    {
     "month": 7,
     "maturity": 0.15,
     "open": true,
     "revenue": 89705,
     "cogs": 24834,
     "opex": 145371,
     "operating": -80500,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": -80500,
     "cumulativeCash": 23388
    },
    {
     "month": 8,
     "maturity": 0.22,
     "open": true,
     "revenue": 131568,
     "cogs": 36424,
     "opex": 145371,
     "operating": -50227,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": -50227,
     "cumulativeCash": -26839
    },
    {
     "month": 9,
     "maturity": 0.3,
     "open": true,
     "revenue": 179411,
     "cogs": 49669,
     "opex": 145371,
     "operating": -15629,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": -15629,
     "cumulativeCash": -42467
    },
    {
     "month": 10,
     "maturity": 0.36,
     "open": true,
     "revenue": 215293,
     "cogs": 59603,
     "opex": 145371,
     "operating": 10320,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 10320,
     "cumulativeCash": -32148
    },
    {
     "month": 11,
     "maturity": 0.42,
     "open": true,
     "revenue": 251175,
     "cogs": 69536,
     "opex": 145371,
     "operating": 36268,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 36268,
     "cumulativeCash": 4120
    },
    {
     "month": 12,
     "maturity": 0.48,
     "open": true,
     "revenue": 287057,
     "cogs": 79470,
     "opex": 145371,
     "operating": 62216,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 62216,
     "cumulativeCash": 66337
    },
    {
     "month": 13,
     "maturity": 0.54,
     "open": true,
     "revenue": 322940,
     "cogs": 89404,
     "opex": 145371,
     "operating": 88165,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 88165,
     "cumulativeCash": 154502
    },
    {
     "month": 14,
     "maturity": 0.58,
     "open": true,
     "revenue": 346861,
     "cogs": 96026,
     "opex": 145371,
     "operating": 105464,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 105464,
     "cumulativeCash": 259966
    },
    {
     "month": 15,
     "maturity": 0.62,
     "open": true,
     "revenue": 370783,
     "cogs": 102649,
     "opex": 145371,
     "operating": 122763,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 122763,
     "cumulativeCash": 382728
    },
    {
     "month": 16,
     "maturity": 0.66,
     "open": true,
     "revenue": 394704,
     "cogs": 109272,
     "opex": 145371,
     "operating": 140062,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 140062,
     "cumulativeCash": 522790
    },
    {
     "month": 17,
     "maturity": 0.7,
     "open": true,
     "revenue": 418625,
     "cogs": 115894,
     "opex": 145371,
     "operating": 157361,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 157361,
     "cumulativeCash": 680151
    },
    {
     "month": 18,
     "maturity": 0.73,
     "open": true,
     "revenue": 436567,
     "cogs": 120861,
     "opex": 151601,
     "operating": 164105,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 164105,
     "cumulativeCash": 844255
    },
    {
     "month": 19,
     "maturity": 0.76,
     "open": true,
     "revenue": 454508,
     "cogs": 125828,
     "opex": 157831,
     "operating": 170849,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 170849,
     "cumulativeCash": 1015104
    },
    {
     "month": 20,
     "maturity": 0.79,
     "open": true,
     "revenue": 472449,
     "cogs": 130795,
     "opex": 164061,
     "operating": 177593,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 177593,
     "cumulativeCash": 1192697
    },
    {
     "month": 21,
     "maturity": 0.82,
     "open": true,
     "revenue": 490390,
     "cogs": 135762,
     "opex": 170291,
     "operating": 184337,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 184337,
     "cumulativeCash": 1377034
    },
    {
     "month": 22,
     "maturity": 0.85,
     "open": true,
     "revenue": 508331,
     "cogs": 140728,
     "opex": 176522,
     "operating": 191081,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 191081,
     "cumulativeCash": 1568114
    },
    {
     "month": 23,
     "maturity": 0.87,
     "open": true,
     "revenue": 520292,
     "cogs": 144040,
     "opex": 180675,
     "operating": 195577,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 195577,
     "cumulativeCash": 1763691
    },
    {
     "month": 24,
     "maturity": 0.89,
     "open": true,
     "revenue": 532252,
     "cogs": 147351,
     "opex": 184829,
     "operating": 200073,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 200073,
     "cumulativeCash": 1963764
    },
    {
     "month": 25,
     "maturity": 0.91,
     "open": true,
     "revenue": 544213,
     "cogs": 150662,
     "opex": 188982,
     "operating": 204569,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 204569,
     "cumulativeCash": 2168333
    },
    {
     "month": 26,
     "maturity": 0.93,
     "open": true,
     "revenue": 556174,
     "cogs": 153973,
     "opex": 193135,
     "operating": 209065,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 209065,
     "cumulativeCash": 2377398
    },
    {
     "month": 27,
     "maturity": 0.94,
     "open": true,
     "revenue": 562154,
     "cogs": 155629,
     "opex": 195212,
     "operating": 211313,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 211313,
     "cumulativeCash": 2588711
    },
    {
     "month": 28,
     "maturity": 0.96,
     "open": true,
     "revenue": 574115,
     "cogs": 158940,
     "opex": 199366,
     "operating": 215809,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 215809,
     "cumulativeCash": 2804519
    },
    {
     "month": 29,
     "maturity": 0.97,
     "open": true,
     "revenue": 580095,
     "cogs": 160596,
     "opex": 201442,
     "operating": 218057,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 218057,
     "cumulativeCash": 3022576
    },
    {
     "month": 30,
     "maturity": 0.98,
     "open": true,
     "revenue": 586076,
     "cogs": 162252,
     "opex": 203519,
     "operating": 220305,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 220305,
     "cumulativeCash": 3242881
    },
    {
     "month": 31,
     "maturity": 0.99,
     "open": true,
     "revenue": 592056,
     "cogs": 163907,
     "opex": 205596,
     "operating": 222553,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 222553,
     "cumulativeCash": 3465434
    },
    {
     "month": 32,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 224801,
     "cumulativeCash": 3690235
    },
    {
     "month": 33,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 224801,
     "cumulativeCash": 3915036
    },
    {
     "month": 34,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 224801,
     "cumulativeCash": 4139837
    },
    {
     "month": 35,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 224801,
     "cumulativeCash": 4364638
    },
    {
     "month": 36,
     "maturity": 1,
     "open": true,
     "revenue": 598036,
     "cogs": 165563,
     "opex": 207673,
     "operating": 224801,
     "debtService": 0,
     "foundingProceeds": 0,
     "netCash": 224801,
     "cumulativeCash": 4589439
    }
   ],
   "breakeven": 10,
   "dscrByYear": [
    {
     "year": 1,
     "operating": -473662,
     "debt": 0,
     "dscr": null,
     "passes": null
    },
    {
     "year": 2,
     "operating": 1897430,
     "debt": 0,
     "dscr": null,
     "passes": null
    },
    {
     "year": 3,
     "operating": 2625676,
     "debt": 0,
     "dscr": null,
     "passes": null
    }
   ],
   "band": [
    {
     "label": "Low",
     "tag": "Slow member ramp, 72% of base volume",
     "revenue": 430586,
     "netAfterCogs": 311381,
     "operating": 103708,
     "annual": 1244500,
     "dscr": null
    },
    {
     "label": "Base",
     "tag": "Stated assumptions at stabilization",
     "revenue": 598036,
     "netAfterCogs": 432473,
     "operating": 224801,
     "annual": 2697611,
     "dscr": null
    },
    {
     "label": "Upside",
     "tag": "Waitlist demand, 128% of base volume",
     "revenue": 765486,
     "netAfterCogs": 553566,
     "operating": 345893,
     "annual": 4150722,
     "dscr": null
    }
   ],
   "scope": {
    "total": 30,
    "licensed": 24,
    "openToAnyone": 6
   },
   "trough": {
    "month": 9,
    "amount": -42467
   },
   "reserve": 1105800,
   "rateStressPasses": null,
   "rateStress": null,
   "cumulativeCash36": 4589439,
   "paybackMonth": {
    "month": 37,
    "extrapolated": true
   }
  }
 }
};
